In [1]:
import numpy as np

data = np.arange(3*16*10).reshape(3,16,10)

print("Original Data")
print(data)



Original Data
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]]

 [[160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 222 2

In [2]:
# Year-wise average
year_avg = np.mean(data, axis=(1,2))
print("Year-wise Average")
print(year_avg)


Year-wise Average
[ 79.5 239.5 399.5]


In [3]:
# Student-wise total
student_total = np.sum(data, axis=2)
print("Student-wise Total")
print(student_total)

Student-wise Total
[[  45  145  245  345  445  545  645  745  845  945 1045 1145 1245 1345
  1445 1545]
 [1645 1745 1845 1945 2045 2145 2245 2345 2445 2545 2645 2745 2845 2945
  3045 3145]
 [3245 3345 3445 3545 3645 3745 3845 3945 4045 4145 4245 4345 4445 4545
  4645 4745]]


In [4]:
# Subject-wise highest score
subject_max = np.max(data, axis=(0,1))
print("Subject-wise Highest Score")
print(subject_max)


Subject-wise Highest Score
[470 471 472 473 474 475 476 477 478 479]


In [5]:
# Replace marks below 40 with 40
data[data < 40] = 40
print("Updated Data")
print(data)


Updated Data
[[[ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]]

 [[160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 222 22

In [6]:
# Sort marks subject-wise
sorted_data = np.sort(data, axis=2)
print("Sorted Marks Subject-wise")
print(sorted_data)

Sorted Marks Subject-wise
[[[ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]]

 [[160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [2